[profile.default]
src = "src"
test = "."
out = "out"
cache_path = "cache"
solc = "0.6.11"
auto_detect_solc = false
allow_paths = ["/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/66"]
libs = ["/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/66/node_modules"]
remappings = ["yeti=/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/66/packages/contracts/contracts/"]