[profile.default]
src = "src"
test = "."
out = "out"
cache_path = "cache"
solc = "0.8.9"
auto_detect_solc = false
allow_paths = ["/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/52"]
libs = ["/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/52/node_modules"]
remappings = [
  "contracts/=/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/52/contracts/",
  "@openzeppelin/contracts=/home/mat/certora-ac-audit/certora-ac-datasets/detasets/web3bugs/dataset/web3bugs/52/node_modules/@openzeppelin/contracts",
]